Repository watertap-org/watertap-reflo, pull requests merged in 2024-01, with the labels that each got.

#85 AirStripping0D and AirWaterEquilibrium Property Model + Docs
  .coveragerc
  docs/_static/unit_models/air_stripping_schematic.png
  docs/technical_reference/index.rst
  docs/technical_reference/property_models/air_water_equilibrium_properties.rst
  docs/technical_reference/property_models/basic_water_properties.rst
  docs/technical_reference/property_models/index.rst
  docs/technical_reference/unit_models/air_stripping.rst
  docs/technical_reference/unit_models/index.rst
  src/watertap_contrib/reflo/costing/units/air_stripping.py
  src/watertap_contrib/reflo/costing/watertap_reflo_costing_package.py
  src/watertap_contrib/reflo/property_models/__init__.py
  src/watertap_contrib/reflo/property_models/air_water_equilibrium_properties.py
  src/watertap_contrib/reflo/property_models/tests/test_air_water_equilibrium_properties.py
  src/watertap_contrib/reflo/unit_models/__init__.py
  src/watertap_contrib/reflo/unit_models/air_stripping_0D.py
  src/watertap_contrib/reflo/unit_models/tests/__init__.py
  src/watertap_contrib/reflo/unit_models/tests/test_air_stripping_0D.py
  src/watertap_contrib/reflo/unit_models/zero_order/tests/test_chemical_softening.py
Labels: enhancement

#92 Simple multiperiod demo
  src/watertap_contrib/reflo/analysis/case_studies/KBHDP/components/__init__.py
  src/watertap_contrib/reflo/code_demos/assets/Balance.png
  src/watertap_contrib/reflo/code_demos/assets/Balance_dark.png
  src/watertap_contrib/reflo/code_demos/assets/MP_Framework.png
  src/watertap_contrib/reflo/code_demos/assets/MP_Framework_2.png
  src/watertap_contrib/reflo/code_demos/assets/Multiperiod.png
  src/watertap_contrib/reflo/code_demos/assets/RO_PV_Batt.png
  src/watertap_contrib/reflo/code_demos/assets/RO_PV_Batt.svg
  src/watertap_contrib/reflo/code_demos/assets/constraint.png
  src/watertap_contrib/reflo/code_demos/assets/constraint_dark.png
  src/watertap_contrib/reflo/code_demos/assets/costing_constraints.png
  src/watertap_contrib/reflo/code_demos/assets/demo_surrogate.json
  src/watertap_contrib/reflo/code_demos/assets/linking.png
  src/watertap_contrib/reflo/code_demos/assets/solar_cycle.png
  src/watertap_contrib/reflo/code_demos/assets/solar_cycle2.png
  src/watertap_contrib/reflo/code_demos/assets/var_table.png
  src/watertap_contrib/reflo/code_demos/multiperiod_demo_final.ipynb
  src/watertap_contrib/reflo/code_demos/steady_state_flowsheets/RO_unit.py
  src/watertap_contrib/reflo/code_demos/steady_state_flowsheets/__init__.py
  src/watertap_contrib/reflo/code_demos/steady_state_flowsheets/simple_RO_unit.py
  src/watertap_contrib/reflo/code_demos/steady_state_flowsheets/system.py
  src/watertap_contrib/reflo/code_demos/util/__init__.py
  src/watertap_contrib/reflo/code_demos/util/visualize.py
  src/watertap_contrib/reflo/unit_models/zero_order/battery.py
  src/watertap_contrib/reflo/unit_models/zero_order/tests/test_battery.py
Labels: documentation, multiperiod

#102 Point to watertap 0.11
  setup.py
Labels: enhancement

#90 Add Documentation for REFLO Models
  docs/_static/WaterTAP-REFLO.png
  docs/_static/watertap_reflo_logo.png
  docs/conf.py
  docs/how_to_guides/how_to_create_surrogate_model_class.rst
  docs/how_to_guides/index.rst
  docs/index.rst
  docs/technical_reference/unit_models/energy_models/flat_plate_collector_physical.rst
  docs/technical_reference/unit_models/energy_models/index.rst
  docs/technical_reference/unit_models/energy_models/pv_surrogate.rst
  docs/technical_reference/unit_models/energy_models/thermal_energy_storage.rst
  docs/technical_reference/unit_models/index.rst
  docs/technical_reference/unit_models/treatment_models/air_stripping.rst
  docs/technical_reference/unit_models/treatment_models/chem_soft.rst
  docs/technical_reference/unit_models/treatment_models/index.rst
  docs/technical_reference/unit_models/treatment_models/lt_med_surrogate.rst
  docs/technical_reference/unit_models/treatment_models/med_tvc_surrogate.rst
  docs/technical_reference/unit_models/treatment_models/vagmd_surrogate_base.rst
Labels: documentation
